import numpy as np
import cv2
from matplotlib import pyplot as plt
'''Test the quality of depth maps based on ground truth depth maps.'''

def normalize_depth(depth_map):
    '''Return the normalized depth maps. '''
    # normalize depth into range of 0-255
    maxi_depth = np.max(depth_map)
    mini_depth = np.min(depth_map)
    depth_map = ((depth_map - mini_depth) / (maxi_depth - mini_depth)) * 255
    return depth_map

def depth_quality(depth_true, depth_map):
    '''Return the error(mean root of SSD) between the
    ground truth depth map and testing depth map'''
    rows,cols = depth_true.shape
    num_pts = rows*cols
    reference = normalize_depth(depth_true)
    plt.imshow(reference,cmap='gray')
    plt.show()
    test = normalize_depth(depth_map)
    plt.imshow(test,cmap='gray')
    plt.show()
    diff = np.subtract(test, reference)
    SSD = np.sum(np.square(diff))
    error = np.sqrt(SSD/num_pts)
    print('Error is, ', error)



if __name__ == '__main__':
    #Test the quality of 2 depth map generated by different models
    depth_true = cv2.imread("ground_truth_DM_0.png")[:,:,0]
    depth_nyu = cv2.imread("../Test_Images/teapot1/depth_nyu.png")[:,:,0]
    depth_kitti = cv2.imread("../Test_Images/teapot1/depth_kitti.png")[:, :, 0]
    rows, cols = depth_nyu.shape
    depth_true = cv2.resize(depth_true, (cols, rows))
    print(depth_true.shape)
    print(depth_nyu.shape)
    depth_quality(depth_true, depth_nyu)
    depth_quality(depth_true, depth_kitti)
